ifcs:
  options:
    log_level: "warn"
nodes:
- node_id: "0"
  options:
    sd_low_power_mode_global_default: "true"
    sku: "configs/sku/teralynx.yaml"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    pt01: "896"
    max_lossless_tc: "2"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    ecmp_hierarchical_enable: "1"
    multicast_lag_resolution_enable: "1"
    led_cfg_sck_rate: "0x5"
    led_refresh_precliff_timer: "0x18eec2"
    led_refresh_cliff_timer: "0x15e"
    led_cfg_pic_stream_mode: "1"
    led_refresh_tmr_ctl_enable: "1"
    bfd_config:
    - offload_enable: "true"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "2, 5, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      queues: "42, 43, 44, 45, 46"
    - rxring_id: "4"
      desc_count: "1024"
      prio: "1"
      queues: "8"
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"
