ifcs:
  options:
    log_level: "warn"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/teralynx.yaml"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    pt01: "896"
    wred_cr_ip_proto_list: "17"
    cr_assignment_mode: "1"
    max_lossless_tc: "2"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    ecmp_hierarchical_enable: "1"
    multicast_lag_resolution_enable: "1"
    skip_pll_check: "false"
    sys_clk: "1800"
    ifc_clk: "1800"
    mac_clk: "1600"
    ecmp_alb_enable: "1"
    alb_port_state_enable: "1"
    ecmp_alb_timeout_step_size: "2"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"
