---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonic-change-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sonic-change-agent
rules:
- apiGroups: ["sonic.k8s.io"]
  resources: ["networkdevices"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["sonic.k8s.io"]
  resources: ["networkdevices/status"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sonic-change-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sonic-change-agent
subjects:
- kind: ServiceAccount
  name: sonic-change-agent
  namespace: default
